version: '3'

networks:
  network:

services:
  db:
    container_name: mssql-db
    image:  mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=pZWnFgA9KjPWQTEx7mdBK7jh7C6JoWpx
    volumes:
      - ./dev/db:/var/opt/mssql/initdb:ro
    ports:
      - 1434:1433
    networks:
      - network
    command: /var/opt/mssql/initdb/command.sh
